version: 2.1

orbs:
  acorn:
    executors:
      php-73:
        docker:
          - image: 'circleci/php:7.3-stretch'
        environment:
          PHP_VERSION: '7.3'
      php-72:
        docker:
          - image: 'circleci/php:7.2-stretch'
        environment:
          PHP_VERSION: '7.2'
    jobs:
      build-php:
        parameters:
          executor:
            type: executor
        executor: << parameters.executor >>
        steps:
          - run: php -v
          - checkout
          - restore_cache:
              keys:
                - v1-php-{{ .Environment.PHP_VERSION }}-{{ checksum "composer.json" }}
                - v1-php-{{ .Environment.PHP_VERSION }}-
                - v1-php-
          - run: composer install -n --prefer-dist --no-scripts --no-suggest
          - run: composer lint
          - run: composer test
          - save_cache:
              key: v1-php-{{ .Environment.PHP_VERSION }}-{{ checksum "composer.json" }}
              paths:
                - vendor

workflows:
  build:
    jobs:
      - acorn/build-php:
          name: build-php-73
          executor: acorn/php-73
      - acorn/build-php:
          name: build-php-72
          executor: acorn/php-72
