name: Publish release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove incompatible dependencies
        run: composer remove pestphp/pest pestphp/pest-plugin-mock spatie/pest-plugin-snapshots --dev --no-interaction
        if: matrix.php < 8
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader --no-dev --no-interaction
      - name: Cleanup unnecessary files
        run: rm -rf .git .github .editorconfig .gitattributes .gitignore composer.json composer.lock phpcs.xml.dist phpunit.xml.dist tests bin
      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Create subfolder
        run: mkdir acorn && mv ./* acorn/ 2>/dev/null
        continue-on-error: true
      - name: Create distributable zip file
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r9 acorn.zip acorn
      - name: Upload zip as release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: acorn.zip
          asset_name: acorn-${{ steps.get_version.outputs.version }}-php-${{ matrix.php-versions }}.zip
          tag: ${{ github.ref }}
          overwrite: true
